// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateModuleData, CreateModuleErrors, CreateModuleResponses, CreateQuizData, CreateQuizErrors, CreateQuizResponses, CreateSectionData, CreateSectionErrors, CreateSectionResponses, DeleteModuleData, DeleteModuleErrors, DeleteModuleResponses, DeleteQuizData, DeleteQuizErrors, DeleteQuizResponses, DeleteSectionData, DeleteSectionErrors, DeleteSectionResponses, EvaluateQuizData, EvaluateQuizErrors, EvaluateQuizResponses, GetModuleData, GetModuleErrors, GetModuleResponses, GetModuleSectionsData, GetModuleSectionsErrors, GetModuleSectionsResponses, GetOwnProfileData, GetOwnProfileErrors, GetOwnProfileResponses, GetProfileData, GetProfileErrors, GetProfileResponses, GetProgressData, GetProgressErrors, GetProgressResponses, GetQuizData, GetQuizErrors, GetQuizResponses, GetQuizResultData, GetQuizResultErrors, GetQuizResultResponses, GetSectionData, GetSectionErrors, GetSectionQuizData, GetSectionQuizErrors, GetSectionQuizResponses, GetSectionResponses, ListModulesData, ListModulesErrors, ListModulesResponses, ListProgressData, ListProgressErrors, ListProgressResponses, ListQuizResultsData, ListQuizResultsErrors, ListQuizResultsResponses, ListQuizzesData, ListQuizzesErrors, ListQuizzesResponses, ListSectionsData, ListSectionsErrors, ListSectionsResponses, StartModuleData, StartModuleErrors, StartModuleResponses, SubmitQuizResultData, SubmitQuizResultErrors, SubmitQuizResultResponses, UpdateModuleData, UpdateModuleErrors, UpdateModuleResponses, UpdateProfileData, UpdateProfileErrors, UpdateProfileResponses, UpdateProgressData, UpdateProgressErrors, UpdateProgressResponses, UpdateQuizData, UpdateQuizErrors, UpdateQuizResponses, UpdateSectionData, UpdateSectionErrors, UpdateSectionResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List published modules
 */
export const listModules = <ThrowOnError extends boolean = false>(options?: Options<ListModulesData, ThrowOnError>) => (options?.client ?? client).get<ListModulesResponses, ListModulesErrors, ThrowOnError>({ url: '/modules', ...options });

/**
 * Create a new module
 */
export const createModule = <ThrowOnError extends boolean = false>(options: Options<CreateModuleData, ThrowOnError>) => (options.client ?? client).post<CreateModuleResponses, CreateModuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/modules',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a module
 */
export const deleteModule = <ThrowOnError extends boolean = false>(options: Options<DeleteModuleData, ThrowOnError>) => (options.client ?? client).delete<DeleteModuleResponses, DeleteModuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/modules/{id}',
    ...options
});

/**
 * Get a single module
 */
export const getModule = <ThrowOnError extends boolean = false>(options: Options<GetModuleData, ThrowOnError>) => (options.client ?? client).get<GetModuleResponses, GetModuleErrors, ThrowOnError>({ url: '/modules/{id}', ...options });

/**
 * Update a module
 */
export const updateModule = <ThrowOnError extends boolean = false>(options: Options<UpdateModuleData, ThrowOnError>) => (options.client ?? client).patch<UpdateModuleResponses, UpdateModuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/modules/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all sections for a module
 */
export const getModuleSections = <ThrowOnError extends boolean = false>(options: Options<GetModuleSectionsData, ThrowOnError>) => (options.client ?? client).get<GetModuleSectionsResponses, GetModuleSectionsErrors, ThrowOnError>({ url: '/modules/{id}/sections', ...options });

/**
 * List sections
 */
export const listSections = <ThrowOnError extends boolean = false>(options?: Options<ListSectionsData, ThrowOnError>) => (options?.client ?? client).get<ListSectionsResponses, ListSectionsErrors, ThrowOnError>({ url: '/sections', ...options });

/**
 * Create a new section
 */
export const createSection = <ThrowOnError extends boolean = false>(options: Options<CreateSectionData, ThrowOnError>) => (options.client ?? client).post<CreateSectionResponses, CreateSectionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/sections',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a section
 */
export const deleteSection = <ThrowOnError extends boolean = false>(options: Options<DeleteSectionData, ThrowOnError>) => (options.client ?? client).delete<DeleteSectionResponses, DeleteSectionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/sections/{id}',
    ...options
});

/**
 * Get a single section
 */
export const getSection = <ThrowOnError extends boolean = false>(options: Options<GetSectionData, ThrowOnError>) => (options.client ?? client).get<GetSectionResponses, GetSectionErrors, ThrowOnError>({ url: '/sections/{id}', ...options });

/**
 * Update a section
 */
export const updateSection = <ThrowOnError extends boolean = false>(options: Options<UpdateSectionData, ThrowOnError>) => (options.client ?? client).patch<UpdateSectionResponses, UpdateSectionErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/sections/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get the quiz for a section
 */
export const getSectionQuiz = <ThrowOnError extends boolean = false>(options: Options<GetSectionQuizData, ThrowOnError>) => (options.client ?? client).get<GetSectionQuizResponses, GetSectionQuizErrors, ThrowOnError>({ url: '/sections/{id}/quiz', ...options });

/**
 * List quizzes
 */
export const listQuizzes = <ThrowOnError extends boolean = false>(options?: Options<ListQuizzesData, ThrowOnError>) => (options?.client ?? client).get<ListQuizzesResponses, ListQuizzesErrors, ThrowOnError>({ url: '/quizzes', ...options });

/**
 * Create a new quiz
 */
export const createQuiz = <ThrowOnError extends boolean = false>(options: Options<CreateQuizData, ThrowOnError>) => (options.client ?? client).post<CreateQuizResponses, CreateQuizErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quizzes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a quiz
 */
export const deleteQuiz = <ThrowOnError extends boolean = false>(options: Options<DeleteQuizData, ThrowOnError>) => (options.client ?? client).delete<DeleteQuizResponses, DeleteQuizErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quizzes/{id}',
    ...options
});

/**
 * Get a single quiz
 */
export const getQuiz = <ThrowOnError extends boolean = false>(options: Options<GetQuizData, ThrowOnError>) => (options.client ?? client).get<GetQuizResponses, GetQuizErrors, ThrowOnError>({ url: '/quizzes/{id}', ...options });

/**
 * Update a quiz
 */
export const updateQuiz = <ThrowOnError extends boolean = false>(options: Options<UpdateQuizData, ThrowOnError>) => (options.client ?? client).patch<UpdateQuizResponses, UpdateQuizErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quizzes/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get your own profile
 */
export const getOwnProfile = <ThrowOnError extends boolean = false>(options?: Options<GetOwnProfileData, ThrowOnError>) => (options?.client ?? client).get<GetOwnProfileResponses, GetOwnProfileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/profiles',
    ...options
});

/**
 * Get a profile by ID (own only)
 */
export const getProfile = <ThrowOnError extends boolean = false>(options: Options<GetProfileData, ThrowOnError>) => (options.client ?? client).get<GetProfileResponses, GetProfileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/profiles/{id}',
    ...options
});

/**
 * Update a profile (own only)
 */
export const updateProfile = <ThrowOnError extends boolean = false>(options: Options<UpdateProfileData, ThrowOnError>) => (options.client ?? client).patch<UpdateProfileResponses, UpdateProfileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/profiles/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List your quiz results
 */
export const listQuizResults = <ThrowOnError extends boolean = false>(options?: Options<ListQuizResultsData, ThrowOnError>) => (options?.client ?? client).get<ListQuizResultsResponses, ListQuizResultsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quiz-results',
    ...options
});

/**
 * Submit a quiz result
 */
export const submitQuizResult = <ThrowOnError extends boolean = false>(options: Options<SubmitQuizResultData, ThrowOnError>) => (options.client ?? client).post<SubmitQuizResultResponses, SubmitQuizResultErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quiz-results',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a single quiz result (own only)
 */
export const getQuizResult = <ThrowOnError extends boolean = false>(options: Options<GetQuizResultData, ThrowOnError>) => (options.client ?? client).get<GetQuizResultResponses, GetQuizResultErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quiz-results/{id}',
    ...options
});

/**
 * Evaluate quiz answers using LLM
 *
 * Evaluates quiz answers against section content. Uses LLM for voice/text questions and direct comparison for multiple choice.
 */
export const evaluateQuiz = <ThrowOnError extends boolean = false>(options: Options<EvaluateQuizData, ThrowOnError>) => (options.client ?? client).post<EvaluateQuizResponses, EvaluateQuizErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/quiz-results/evaluate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List your module progress
 */
export const listProgress = <ThrowOnError extends boolean = false>(options?: Options<ListProgressData, ThrowOnError>) => (options?.client ?? client).get<ListProgressResponses, ListProgressErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/progress',
    ...options
});

/**
 * Start a module (create progress)
 */
export const startModule = <ThrowOnError extends boolean = false>(options: Options<StartModuleData, ThrowOnError>) => (options.client ?? client).post<StartModuleResponses, StartModuleErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/progress',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a progress record (own only)
 */
export const getProgress = <ThrowOnError extends boolean = false>(options: Options<GetProgressData, ThrowOnError>) => (options.client ?? client).get<GetProgressResponses, GetProgressErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/progress/{id}',
    ...options
});

/**
 * Update progress (own only)
 */
export const updateProgress = <ThrowOnError extends boolean = false>(options: Options<UpdateProgressData, ThrowOnError>) => (options.client ?? client).patch<UpdateProgressResponses, UpdateProgressErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/progress/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
