// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type Difficulty = 'beginner' | 'intermediate' | 'advanced';

export type QuestionInputType = 'text' | 'voice' | 'multiple_choice';

export type ProgressStatus = 'in_progress' | 'completed';

export type Profile = {
    id: string;
    email: string;
    display_name?: string;
    avatar_url?: string;
    created_at: string;
    updated_at: string;
};

export type Module = {
    id: string;
    title: string;
    description: string;
    topic: string;
    difficulty: Difficulty;
    estimated_duration_mins: number;
    thumbnail_url?: string;
    is_published: boolean;
    created_at: string;
    updated_at: string;
};

export type Section = {
    id: string;
    module_id: string;
    title: string;
    content: string;
    order_index: number;
    audio_url?: string;
    created_at: string;
    updated_at: string;
};

export type QuizQuestion = {
    id: string;
    question_text: string;
    input_type: QuestionInputType;
    options?: Array<string>;
    correct_answer?: string;
    order_index: number;
};

export type Quiz = {
    id: string;
    section_id: string;
    title: string;
    questions: Array<QuizQuestion>;
    created_at: string;
    updated_at: string;
};

export type QuizAnswer = {
    question_id: string;
    user_response: string;
    is_correct?: boolean;
};

export type QuizResult = {
    id: string;
    user_id: string;
    quiz_id: string;
    score: number;
    answers: Array<QuizAnswer>;
    completed_at: string;
    created_at: string;
};

export type UserModuleProgress = {
    id: string;
    user_id: string;
    module_id: string;
    status: ProgressStatus;
    current_section_index: number;
    started_at: string;
    completed_at?: string;
};

export type Pagination = {
    total: number;
    limit: number;
    offset: number;
    hasMore: boolean;
};

export type ApiError = {
    success: false;
    error: string;
    details?: string;
};

export type ModuleCreate = {
    title: string;
    description: string;
    topic: string;
    difficulty: Difficulty;
    estimated_duration_mins?: number;
    thumbnail_url?: string;
    is_published?: boolean;
};

export type ModuleUpdate = {
    title?: string;
    description?: string;
    topic?: string;
    difficulty?: Difficulty;
    estimated_duration_mins?: number;
    thumbnail_url?: string;
    is_published?: boolean;
};

export type SectionCreate = {
    module_id: string;
    title: string;
    content: string;
    order_index: number;
};

export type SectionUpdate = {
    title?: string;
    content?: string;
    order_index?: number;
};

export type QuizCreate = {
    section_id: string;
    title: string;
    questions?: Array<QuizQuestion>;
};

export type QuizUpdate = {
    title?: string;
    questions?: Array<QuizQuestion>;
};

export type ProfileUpdate = {
    display_name?: string;
    avatar_url?: string;
};

export type QuizResultCreate = {
    quiz_id: string;
    score: number;
    answers: Array<QuizAnswer>;
};

export type ProgressCreate = {
    module_id: string;
};

export type ProgressUpdate = {
    status?: ProgressStatus;
    current_section_index?: number;
    completed_at?: string;
};

export type QuizEvaluationAnswerInput = {
    question_id: string;
    user_response: string;
};

export type QuizEvaluationRequest = {
    quiz_id: string;
    answers: Array<QuizEvaluationAnswerInput>;
};

export type QuizEvaluationResponse = {
    score: number;
    feedback: string;
    answers: Array<QuizAnswer>;
};

export type ListModulesData = {
    body?: never;
    path?: never;
    query?: {
        topic?: string;
        difficulty?: Difficulty;
        limit?: number;
        offset?: number;
    };
    url: '/modules';
};

export type ListModulesErrors = {
    /**
     * Server error
     */
    500: ApiError;
};

export type ListModulesError = ListModulesErrors[keyof ListModulesErrors];

export type ListModulesResponses = {
    /**
     * List of modules
     */
    200: {
        success: true;
        data: Array<Module>;
        pagination: Pagination;
    };
};

export type ListModulesResponse = ListModulesResponses[keyof ListModulesResponses];

export type CreateModuleData = {
    body: ModuleCreate;
    path?: never;
    query?: never;
    url: '/modules';
};

export type CreateModuleErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
};

export type CreateModuleError = CreateModuleErrors[keyof CreateModuleErrors];

export type CreateModuleResponses = {
    /**
     * Module created
     */
    201: {
        success: true;
        data: Module;
    };
};

export type CreateModuleResponse = CreateModuleResponses[keyof CreateModuleResponses];

export type DeleteModuleData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/modules/{id}';
};

export type DeleteModuleErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteModuleError = DeleteModuleErrors[keyof DeleteModuleErrors];

export type DeleteModuleResponses = {
    /**
     * Module deleted
     */
    204: void;
};

export type DeleteModuleResponse = DeleteModuleResponses[keyof DeleteModuleResponses];

export type GetModuleData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/modules/{id}';
};

export type GetModuleErrors = {
    /**
     * Module not found
     */
    404: ApiError;
};

export type GetModuleError = GetModuleErrors[keyof GetModuleErrors];

export type GetModuleResponses = {
    /**
     * Module details
     */
    200: {
        success: true;
        data: Module;
    };
};

export type GetModuleResponse = GetModuleResponses[keyof GetModuleResponses];

export type UpdateModuleData = {
    body: ModuleUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/modules/{id}';
};

export type UpdateModuleErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Module not found
     */
    404: ApiError;
};

export type UpdateModuleError = UpdateModuleErrors[keyof UpdateModuleErrors];

export type UpdateModuleResponses = {
    /**
     * Module updated
     */
    200: {
        success: true;
        data: Module;
    };
};

export type UpdateModuleResponse = UpdateModuleResponses[keyof UpdateModuleResponses];

export type GetModuleSectionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/modules/{id}/sections';
};

export type GetModuleSectionsErrors = {
    /**
     * Module not found
     */
    404: ApiError;
};

export type GetModuleSectionsError = GetModuleSectionsErrors[keyof GetModuleSectionsErrors];

export type GetModuleSectionsResponses = {
    /**
     * List of sections
     */
    200: {
        success: true;
        data: Array<Section>;
    };
};

export type GetModuleSectionsResponse = GetModuleSectionsResponses[keyof GetModuleSectionsResponses];

export type ListSectionsData = {
    body?: never;
    path?: never;
    query?: {
        module_id?: string;
        limit?: number;
        offset?: number;
    };
    url: '/sections';
};

export type ListSectionsErrors = {
    /**
     * Server error
     */
    500: ApiError;
};

export type ListSectionsError = ListSectionsErrors[keyof ListSectionsErrors];

export type ListSectionsResponses = {
    /**
     * List of sections
     */
    200: {
        success: true;
        data: Array<Section>;
        pagination: Pagination;
    };
};

export type ListSectionsResponse = ListSectionsResponses[keyof ListSectionsResponses];

export type CreateSectionData = {
    body: SectionCreate;
    path?: never;
    query?: never;
    url: '/sections';
};

export type CreateSectionErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Conflict (duplicate order_index)
     */
    409: ApiError;
};

export type CreateSectionError = CreateSectionErrors[keyof CreateSectionErrors];

export type CreateSectionResponses = {
    /**
     * Section created
     */
    201: {
        success: true;
        data: Section;
    };
};

export type CreateSectionResponse = CreateSectionResponses[keyof CreateSectionResponses];

export type DeleteSectionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sections/{id}';
};

export type DeleteSectionErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteSectionError = DeleteSectionErrors[keyof DeleteSectionErrors];

export type DeleteSectionResponses = {
    /**
     * Section deleted
     */
    204: void;
};

export type DeleteSectionResponse = DeleteSectionResponses[keyof DeleteSectionResponses];

export type GetSectionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sections/{id}';
};

export type GetSectionErrors = {
    /**
     * Section not found
     */
    404: ApiError;
};

export type GetSectionError = GetSectionErrors[keyof GetSectionErrors];

export type GetSectionResponses = {
    /**
     * Section details
     */
    200: {
        success: true;
        data: Section;
    };
};

export type GetSectionResponse = GetSectionResponses[keyof GetSectionResponses];

export type UpdateSectionData = {
    body: SectionUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/sections/{id}';
};

export type UpdateSectionErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Section not found
     */
    404: ApiError;
    /**
     * Conflict (duplicate order_index)
     */
    409: ApiError;
};

export type UpdateSectionError = UpdateSectionErrors[keyof UpdateSectionErrors];

export type UpdateSectionResponses = {
    /**
     * Section updated
     */
    200: {
        success: true;
        data: Section;
    };
};

export type UpdateSectionResponse = UpdateSectionResponses[keyof UpdateSectionResponses];

export type GetSectionQuizData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/sections/{id}/quiz';
};

export type GetSectionQuizErrors = {
    /**
     * Section or quiz not found
     */
    404: ApiError;
};

export type GetSectionQuizError = GetSectionQuizErrors[keyof GetSectionQuizErrors];

export type GetSectionQuizResponses = {
    /**
     * Quiz details
     */
    200: {
        success: true;
        data: Quiz;
    };
};

export type GetSectionQuizResponse = GetSectionQuizResponses[keyof GetSectionQuizResponses];

export type ListQuizzesData = {
    body?: never;
    path?: never;
    query?: {
        section_id?: string;
        limit?: number;
        offset?: number;
    };
    url: '/quizzes';
};

export type ListQuizzesErrors = {
    /**
     * Server error
     */
    500: ApiError;
};

export type ListQuizzesError = ListQuizzesErrors[keyof ListQuizzesErrors];

export type ListQuizzesResponses = {
    /**
     * List of quizzes
     */
    200: {
        success: true;
        data: Array<Quiz>;
        pagination: Pagination;
    };
};

export type ListQuizzesResponse = ListQuizzesResponses[keyof ListQuizzesResponses];

export type CreateQuizData = {
    body: QuizCreate;
    path?: never;
    query?: never;
    url: '/quizzes';
};

export type CreateQuizErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Quiz already exists for this section
     */
    409: ApiError;
};

export type CreateQuizError = CreateQuizErrors[keyof CreateQuizErrors];

export type CreateQuizResponses = {
    /**
     * Quiz created
     */
    201: {
        success: true;
        data: Quiz;
    };
};

export type CreateQuizResponse = CreateQuizResponses[keyof CreateQuizResponses];

export type DeleteQuizData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/quizzes/{id}';
};

export type DeleteQuizErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type DeleteQuizError = DeleteQuizErrors[keyof DeleteQuizErrors];

export type DeleteQuizResponses = {
    /**
     * Quiz deleted
     */
    204: void;
};

export type DeleteQuizResponse = DeleteQuizResponses[keyof DeleteQuizResponses];

export type GetQuizData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/quizzes/{id}';
};

export type GetQuizErrors = {
    /**
     * Quiz not found
     */
    404: ApiError;
};

export type GetQuizError = GetQuizErrors[keyof GetQuizErrors];

export type GetQuizResponses = {
    /**
     * Quiz details
     */
    200: {
        success: true;
        data: Quiz;
    };
};

export type GetQuizResponse = GetQuizResponses[keyof GetQuizResponses];

export type UpdateQuizData = {
    body: QuizUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/quizzes/{id}';
};

export type UpdateQuizErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Quiz not found
     */
    404: ApiError;
};

export type UpdateQuizError = UpdateQuizErrors[keyof UpdateQuizErrors];

export type UpdateQuizResponses = {
    /**
     * Quiz updated
     */
    200: {
        success: true;
        data: Quiz;
    };
};

export type UpdateQuizResponse = UpdateQuizResponses[keyof UpdateQuizResponses];

export type GetOwnProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/profiles';
};

export type GetOwnProfileErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Profile not found
     */
    404: ApiError;
};

export type GetOwnProfileError = GetOwnProfileErrors[keyof GetOwnProfileErrors];

export type GetOwnProfileResponses = {
    /**
     * Profile details
     */
    200: {
        success: true;
        data: Profile;
    };
};

export type GetOwnProfileResponse = GetOwnProfileResponses[keyof GetOwnProfileResponses];

export type GetProfileData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/profiles/{id}';
};

export type GetProfileErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Profile not found
     */
    404: ApiError;
};

export type GetProfileError = GetProfileErrors[keyof GetProfileErrors];

export type GetProfileResponses = {
    /**
     * Profile details
     */
    200: {
        success: true;
        data: Profile;
    };
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type UpdateProfileData = {
    body: ProfileUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/profiles/{id}';
};

export type UpdateProfileErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Forbidden
     */
    403: ApiError;
    /**
     * Profile not found
     */
    404: ApiError;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    /**
     * Profile updated
     */
    200: {
        success: true;
        data: Profile;
    };
};

export type UpdateProfileResponse = UpdateProfileResponses[keyof UpdateProfileResponses];

export type ListQuizResultsData = {
    body?: never;
    path?: never;
    query?: {
        quiz_id?: string;
        limit?: number;
        offset?: number;
    };
    url: '/quiz-results';
};

export type ListQuizResultsErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type ListQuizResultsError = ListQuizResultsErrors[keyof ListQuizResultsErrors];

export type ListQuizResultsResponses = {
    /**
     * List of quiz results
     */
    200: {
        success: true;
        data: Array<QuizResult>;
        pagination: Pagination;
    };
};

export type ListQuizResultsResponse = ListQuizResultsResponses[keyof ListQuizResultsResponses];

export type SubmitQuizResultData = {
    body: QuizResultCreate;
    path?: never;
    query?: never;
    url: '/quiz-results';
};

export type SubmitQuizResultErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
};

export type SubmitQuizResultError = SubmitQuizResultErrors[keyof SubmitQuizResultErrors];

export type SubmitQuizResultResponses = {
    /**
     * Quiz result submitted
     */
    201: {
        success: true;
        data: QuizResult;
    };
};

export type SubmitQuizResultResponse = SubmitQuizResultResponses[keyof SubmitQuizResultResponses];

export type GetQuizResultData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/quiz-results/{id}';
};

export type GetQuizResultErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Quiz result not found
     */
    404: ApiError;
};

export type GetQuizResultError = GetQuizResultErrors[keyof GetQuizResultErrors];

export type GetQuizResultResponses = {
    /**
     * Quiz result details
     */
    200: {
        success: true;
        data: QuizResult;
    };
};

export type GetQuizResultResponse = GetQuizResultResponses[keyof GetQuizResultResponses];

export type EvaluateQuizData = {
    body: QuizEvaluationRequest;
    path?: never;
    query?: never;
    url: '/quiz-results/evaluate';
};

export type EvaluateQuizErrors = {
    /**
     * Invalid input (missing fields or answers)
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Quiz not found
     */
    404: ApiError;
    /**
     * Evaluation failed
     */
    500: ApiError;
};

export type EvaluateQuizError = EvaluateQuizErrors[keyof EvaluateQuizErrors];

export type EvaluateQuizResponses = {
    /**
     * Evaluation result with score and feedback
     */
    200: {
        success: true;
        data: QuizEvaluationResponse;
    };
};

export type EvaluateQuizResponse = EvaluateQuizResponses[keyof EvaluateQuizResponses];

export type ListProgressData = {
    body?: never;
    path?: never;
    query?: {
        module_id?: string;
        status?: ProgressStatus;
        limit?: number;
        offset?: number;
    };
    url: '/progress';
};

export type ListProgressErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Server error
     */
    500: ApiError;
};

export type ListProgressError = ListProgressErrors[keyof ListProgressErrors];

export type ListProgressResponses = {
    /**
     * List of progress records
     */
    200: {
        success: true;
        data: Array<UserModuleProgress>;
        pagination: Pagination;
    };
};

export type ListProgressResponse = ListProgressResponses[keyof ListProgressResponses];

export type StartModuleData = {
    body: ProgressCreate;
    path?: never;
    query?: never;
    url: '/progress';
};

export type StartModuleErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Progress already exists
     */
    409: ApiError;
};

export type StartModuleError = StartModuleErrors[keyof StartModuleErrors];

export type StartModuleResponses = {
    /**
     * Progress created
     */
    201: {
        success: true;
        data: UserModuleProgress;
    };
};

export type StartModuleResponse = StartModuleResponses[keyof StartModuleResponses];

export type GetProgressData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/progress/{id}';
};

export type GetProgressErrors = {
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Progress not found
     */
    404: ApiError;
};

export type GetProgressError = GetProgressErrors[keyof GetProgressErrors];

export type GetProgressResponses = {
    /**
     * Progress details
     */
    200: {
        success: true;
        data: UserModuleProgress;
    };
};

export type GetProgressResponse = GetProgressResponses[keyof GetProgressResponses];

export type UpdateProgressData = {
    body: ProgressUpdate;
    path: {
        id: string;
    };
    query?: never;
    url: '/progress/{id}';
};

export type UpdateProgressErrors = {
    /**
     * Invalid input
     */
    400: ApiError;
    /**
     * Unauthorized
     */
    401: ApiError;
    /**
     * Progress not found
     */
    404: ApiError;
};

export type UpdateProgressError = UpdateProgressErrors[keyof UpdateProgressErrors];

export type UpdateProgressResponses = {
    /**
     * Progress updated
     */
    200: {
        success: true;
        data: UserModuleProgress;
    };
};

export type UpdateProgressResponse = UpdateProgressResponses[keyof UpdateProgressResponses];
